baseurl: "https://boloboloda.github.io/"
languageCode: "en-us"
title: "1scream's blog"
theme: "hugo-tania"

rssLimit: 100                # limit number of entries in RSS feeds
page_view_conter: true

# Pagination
# number of entries per page for archives, tags and categories
# since we don't have list view, recommend a large value
paginate: 20
paginatePath: "page"

disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji:

  # Logo will show before the blog title on site navbar.
  titleLogo: 
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email: "cocoq1ngyu@qq.com"
    facebook:
    github: "https://github.com/boloboloda"
    instagram:
    linkedin:
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter:
    twitch:
    whatsapp:

menu:
  header:
    - name: Articles
      url: "/articles/"
  footer:
    - name: RSS
      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]